name: publish

on: [push]

jobs:
  build-and-push-image:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build docker image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx build --platform ${{ matrix.arch }} -t ghcr.io/rjpadilla/hello:${{ matrix.arch }} .
          docker push ghcr.io/rjpadilla/hello:${{ matrix.arch }}