name: publish

on: [push]

jobs:
  build-and-push-image:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm, arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}

      - name: Log in to the Container registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build docker image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          case ${{ matrix.arch }} in
            amd64) : "amd64" ;;
            arm) : "arm32v6" ;;
            arm64) : "arm64v8" ;;
          esac
          arch="$_"
          docker buildx build -t ghcr.io/rjpadilla/hello:${{ matrix.arch }} --build-arg ARCH=$arch . 
          docker push ghcr.io/rjpadilla/hello:${{ matrix.arch }}
          docker build  -t rjpadilla/hello:${{ matrix.arch }} --build-arg ARCH=$arch . 
          docker push rjpadilla/hello:${{ matrix.arch }}
          docker images
  
  build-and-push-manifest:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}

      - name: Deploying manifest to Github Packages
        run: |
          docker images
          docker manifest create ghcr.io/rjpadilla/hello:latest ghcr.io/rjpadilla/hello:amd64 ghcr.io/rjpadilla/hello:arm ghcr.io/rjpadilla/hello:arm64
          docker manifest inspect ghcr.io/rjpadilla/hello:latest
          docker manifest annotate ghcr.io/rjpadilla/hello:latest ghcr.io/rjpadilla/hello:arm --os linux --arch arm 
          docker manifest inspect ghcr.io/rjpadilla/hello:latest
          docker manifest push ghcr.io/rjpadilla/hello:latest

      - name: Deploying manifest to Docker hub
        run: |
          docker images
          docker manifest create rjpadilla/hello:latest rjpadilla/hello:amd64 rjpadilla/hello:arm rjpadilla/hello:arm64
          docker manifest inspect rjpadilla/hello:latest
          docker manifest annotate rjpadilla/hello:latest rjpadilla/hello:arm --os linux --arch arm 
          docker manifest inspect rjpadilla/hello:latest
          docker manifest push rjpadilla/hello:latest


      
